UMBRAL_Z_SCORE = 3
UMBRAL_TRANSACCIONES_RAFAGA= 5
VENTANA_MINUTOS_RAFAGA=60
UMBRAL_SCORE_FRAUDE= 50
NUM_CLIENTES= 100
NUM_TRANSACCIONES=5000
RUTA_RAW = "data/raw/transacciones.csv"
RUTA_OUTPUT = "data/output/reporte_fraude.csv"